#!/usr/bin/env python3 

import tornado.ioloop
import tornado.web
import pprint
import sys

class MyDumpHandler(tornado.web.RequestHandler):
    def post(self):
        pprint.pprint(self.request)
        pprint.pprint(self.request.body)

if __name__ == "__main__":
    print("listing at port 8083\n")
    sys.stdout.flush()
    tornado.web.Application([(r"/.*", MyDumpHandler),]).listen(8083)
    tornado.ioloop.IOLoop.instance().start()
